# Generated by Django 2.0.13 on 2019-08-21 10:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=250)),
                ('dep_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('experience', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('team_work', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('name', models.CharField(max_length=250)),
                ('app_date', models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 36, 47, 213800), verbose_name='date applied')),
                ('votes', models.IntegerField(default=0)),
                ('is_favourite', models.BooleanField(default=False)),
                ('is_accepted', models.IntegerField(default=0)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('inter_date', models.DateField(help_text='format : YYYY-MM-DD', max_length=10, null=True)),
                ('resume', models.FileField(upload_to='', validators=[forum.validators.validate_file_extension])),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Advisor')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Department')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default-picture_0_0.png', null=True, upload_to='')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Intern'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Intern'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisor',
            name='advisor_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Department'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
