# Generated by Django 2.0.13 on 2019-08-21 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190821_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='app_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 49, 45, 738225), verbose_name='date applied'),
        ),
    ]
