# Generated by Django 2.0.13 on 2019-08-21 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190821_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='intern',
            name='app_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 49, 54, 558592), verbose_name='date applied'),
        ),
    ]
