# Generated by Django 2.0.13 on 2019-08-21 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20190821_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterField(
            model_name='intern',
            name='app_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 52, 14, 651227), verbose_name='date applied'),
        ),
    ]
