# Generated by Django 2.0.13 on 2019-08-21 10:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_auto_20190821_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=160)),
            ],
        ),
        migrations.AlterField(
            model_name='intern',
            name='app_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 53, 6, 901351), verbose_name='date applied'),
        ),
        migrations.AddField(
            model_name='comment',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Intern'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
