# Generated by Django 2.0.13 on 2019-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20190821_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='app_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date applied'),
        ),
    ]
