# Generated by Django 2.0.13 on 2019-08-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20190822_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='profile_photo',
            field=models.ImageField(blank=True, default='media/default-picture_0_0.png', null=True, upload_to=''),
        ),
    ]
