# Generated by Django 2.0.13 on 2019-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20190823_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default-picture_0_0.png', null=True, upload_to=''),
        ),
    ]
